### ISSUE TITLE
Lag issue when using upgrades

### ISSUE THREAD

**Issue by Ashley123477** [henkelmax/pipez#179] opened 2023-04-23 08:12 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
When using upgrades on pipez they seem to produce more and more lag dependant on what they are pulling, using observable we noticed as much as 220390 us/t using the infinity upgrades which dropped tps between 6 and 8

**Steps to reproduce the issue**
1. Pipe out of an infinite source
2. Insert infinity upgrade, the smaller upgrades do produce lag just on a smaller scale
3. Observe lag

**Expected behavior**
Pipes to not produce as much lag

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.18.2
- 40.2.1
- pipez-1.18.2-1.1.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.
[modlist.txt](https://github.com/henkelmax/pipez/files/11303168/modlist.txt)
![2023-04-22_20 22 47](https://user-images.githubusercontent.com/26034936/233828086-4dd042b5-6761-4220-84e3-607bdfa3ed0a.png)

**Comment by henkelmax** [comment] 2023-04-23 09:02
Duplicate of #139

**Closed by henkelmax** 2023-04-23 09:02 UTC
Labels: bug
