### ISSUE TITLE
Input/Output option from the same connection

### ISSUE THREAD

**Issue by Eluinees** [henkelmax/pipez#48] opened 2021-06-10 20:58 UTC
Hello!
Just wanted to suggest making it so you can insert and extract things from the same connection.
Like extracting items but inserting energy as it would make it way smoother and easier making huge setups with multiple machines without causing it to look absolutely horrible..
Cheers :D

**Comment by henkelmax** [comment] 2021-06-10 22:04
Duplicate of #43

**Closed by henkelmax** 2021-06-10 22:04 UTC
Labels: enhancement

**Comment by Eluinees** [comment] 2021-06-10 22:09
Was not asking if it was possible as i've already come to that conclusion myself. What i am asking though is if it would be possible to add.

**Comment by henkelmax** [comment] 2021-06-11 05:24
No.
Due to some side effects this would be very hard to add.
