### ISSUE TITLE
Want Input/Output on the same connection.

### ISSUE THREAD

**Issue by Eluinees** [henkelmax/pipez#49] opened 2021-06-11 00:31 UTC
**Is your feature request related to a problem? Please describe.**
Concidering you are not able to extract and insert from the same connection which causes the setups for machines to be obnoxiously large and ugly as there is no easy way to hide cables if you need more than 1 connection.

**Describe the solution you'd like**
Allow us to extract items/Liquids/Gas/Energy and Insert on the same connection without needing another connection.

**Describe alternatives you've considered**
Using another mod.

**Additional context**
Just hope it'll be considered.

**Comment by henkelmax** [comment] 2021-06-11 05:25
Duplicate of #48

**Closed by henkelmax** 2021-06-11 05:25 UTC
Labels: enhancement
