### ISSUE TITLE
[1.16.5] StackOverflow when having a cable loop with Powah cables

### ISSUE THREAD

**Issue by Raidobw2** [henkelmax/pipez#102] opened 2022-02-27 03:00 UTC
**Bug description**
Connecting Powah and Pipez cables in a loop and setting a side of Pipez cables to extract power will start an infinite amount of function calls.

**Steps to reproduce the issue**
1. Place 2 * Powah cable (any rank) and 2 * Pipez energy cable or universal cable. (see screenshot 1)
2. Provide energy to the Powah cable, make sure there is energy moving.
3. Use a wrench to connect the Powah cable and Pipez cable.
4. Game crashed. Loading the same chunk will cause crash again.

**Expected behavior**
That they interact correctly with each other on every tick but that they don't trigger an infinite call loop in a tick.

**Log files**
https://bytebin.lucko.me/lkbgK5HACr

**Versions**
- Minecraft `1.16.5`
- Forge `36.2.22`
- Pipez `pipez-1.16.5-1.2.15.jar` (latest as of now)
- Powah `Powah-1.16.5-2.3.16.jar`
- Lollipop `Lollipop-1.16.5-3.2.9.jar`
- Modpack: FTB Academy 1.16 version 1.3.0

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/17010632/155866299-8f0f8060-2a64-46d1-8fe2-c029fd363b57.png)
![image](https://user-images.githubusercontent.com/17010632/155866305-cf71ca30-cb01-47ac-8bc8-3b1f0684dce0.png)

**Additional information**
Relayed from FTBTeam/FTB-Modpack-Issues#650 and thanks!

**Comment by henkelmax** [comment] 2022-02-27 10:46
Duplicate of #33

**Closed by henkelmax** 2022-02-27 10:46 UTC
Labels: bug
