### ISSUE TITLE
Feature request: Pipez to connect to Vanilla MC Cauldrons

### ISSUE THREAD

**Issue by ryu2065** [henkelmax/pipez#153] opened 2022-11-09 17:15 UTC
I would like to suggest a feature request for this amazing mod. 

I would like fluid pipez to connect to Vanilla MC Cauldrons. Currently there is only the option using buckets by hand or a Create mechanical pump to extract fluid from them. 

I know this is a very niche request, but its one that I feel is a quality of life upgrade.

Thank you for your time.
-Ryu2065

**Comment by henkelmax** [comment] 2022-11-09 22:25
Duplicate of #93

**Closed by henkelmax** 2022-11-09 22:25 UTC
Labels: enhancement
