### ISSUE TITLE
Gas Pipes don't recognize Slurries (Mekanism Integration)

### ISSUE THREAD

**Issue by ConnorMiner** [henkelmax/pipez#174] opened 2023-04-02 03:43 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Gas/Universal Pipes are unable to transport slurries, and won't even connect to slurry outputs

**Steps to reproduce the issue**
- Gas Pipes don't connect to Slurry transport
1. Place down a Chemical Washer
2. Place a Gas Pipe next to it
3. Notice the lack of connection.
- Gas Pipes cannot transport Slurries
1. Place down a Chemical Tank with Slurry in it
2. Place a Gas Pipe next to it set to extract from it
3. Place a second Chemical Tank next to the pipe in order to accept the Slurry
4. Slurry stays in the first tank

**Expected behavior**
Gas Pipes should be able to handle anything Pressurized Tubes are capable of handling.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

The log has no mentions of any issues.

**Versions**
- Minecraft version: 1.18.2
- Forge version: 40.1.73
- Mod version: 1.1.5

**Other mods**
Modpack: Mechanical Mastery
- Mekanism

**Screenshots (Optional)**
![2023-04-01_21 37 50](https://user-images.githubusercontent.com/32756365/229329896-1e82e405-5444-4a9e-849d-0b74a94c48b2.png)
![2023-04-01_21 37 52](https://user-images.githubusercontent.com/32756365/229329897-230da0c2-c216-480b-b313-1e54a48b2a2b.png)
![2023-04-01_21 37 53](https://user-images.githubusercontent.com/32756365/229329898-e7964803-59b7-471b-8f57-f7c34a923d15.png)
![2023-04-01_21 37 54](https://user-images.githubusercontent.com/32756365/229329899-04f7f10c-3ee2-47c4-96b5-d09f369a4f81.png)
![2023-04-01_21 37 56](https://user-images.githubusercontent.com/32756365/229329900-4835447b-3dd7-4bee-b2bd-4c70f334b198.png)

![2023-04-01_21 41 28](https://user-images.githubusercontent.com/32756365/229330024-cc364a81-f2b1-4128-a421-675ded513619.png)
![2023-04-01_21 41 31](https://user-images.githubusercontent.com/32756365/229330025-a076000e-93c5-4f42-9c3e-6ad68d8fd549.png)

**Comment by henkelmax** [comment] 2023-04-02 12:18
Duplicate of #115

**Closed by henkelmax** 2023-04-02 12:18 UTC
Labels: bug
