### ISSUE TITLE
Pipez 1.2.7 and flux plug incompatible

### ISSUE THREAD

**Issue by Nagispace** [henkelmax/pipez#70] opened 2021-09-17 16:14 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Pipez energy pipe not connecting to Flux Networks' flux plug

**Steps to reproduce the issue**
1. Have energy source transferred using pipez
2. Connect flux plug to inject into flux network

**Expected behavior**
Energy going into the flux plug so that it goes in the flux network

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.2
- Mod version 1.2.7

**Other mods**
All The Mods 6 To The Sky Modpack

**Screenshots (Optional)**
Screenshots of the issue.

![image](https://user-images.githubusercontent.com/65559593/133820397-f7d3e688-648a-497f-8b7c-161faf3e8b34.png)
![image](https://user-images.githubusercontent.com/65559593/133820472-3c49932d-7609-4418-91fc-5e500035eb4f.png)

**Comment by henkelmax** [comment] 2021-09-17 16:45
Duplicate of #20

**Closed by henkelmax** 2021-09-17 16:45 UTC
Labels: bug
