### ISSUE TITLE
Gas pipes cannot transport Mekanism slurries

### ISSUE THREAD

**Issue by DeleteMetaInf** [henkelmax/pipez#138] opened 2022-08-25 02:17 UTC
Gas pipes from Pipez are unable to carry slurries from [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism), even though they’re considered a gas. Fluid pipes can’t carry them either, so there’s no way to transport Mekanism slurries with Pipez. And whilst I haven’t tried it, I would presume that Pipez’ gas pipes would be unable to transport Mekanism’s pigment and infuse type gases as well.

This might not be considered a bug per se, since slurries, pigments, and infuse types are somewhat separate from gases in Mekanism, but they _are_ a type of gas, and they’re transported with the same type of pressurized tubes as gases are, and they’re stored in the same type of chemical tanks as gases are as well.

Here is a Mekanism chemical tank filled with dirty osmium slurry, and Pipez’ gas pipe won’t connect to the output side, but Mekanism’s pressurized tubes can connect just fine.

![2022-08-25_04 12 21](https://user-images.githubusercontent.com/59761487/186558677-0b2c3905-e101-4aa4-948b-218a3bc99aed.png)

### Versions

* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (version 0.4.29—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Pipez:** 1.1.5 (latest for 1.18.2)
* **Mekanism:** 10.2.5.465 (latest for 1.18.2)

**Comment by craftingmod** [comment] 2022-08-25 07:23
![image](https://user-images.githubusercontent.com/9389278/186601202-dd7de74e-9c08-4047-8aea-6dc058ef8666.png)

I don't support other capabilities for now. I would try to implement other capabilities after caching bug fix.

A note, if more capabilities are assigned, more tps might be consumed even if there's no any supported capabilities.

**Comment by henkelmax** [comment] 2022-08-25 07:59
Duplicate of #115

**Closed by henkelmax** 2022-08-25 07:59 UTC
Labels: bug
