### ISSUE TITLE
Server Crash Loop minecraft 1.18.1 / ATM 7 0.2.34 - Pipez/tesseract interaction link

### ISSUE THREAD

**Issue by D0ucheos** [henkelmax/pipez#97] opened 2022-01-22 09:26 UTC
I am unable to reproduce the error as my server goes into a crash loop.

We were tidying up our base using pipez and the tesseract to move power and items about and it inexplicably started to crash.

It was working fine for 36 hours after we updated. Server was updated 21/01/22 10:00 AEST (GMT +10)

I have attached the first 4 crash files to the ticket, they repeat in size and included data, in a rolling loop. Current date and time 22/01/22 19:23 AEST (GMT +10)

[crash-2022-01-22_17.10.03-server.txt](https://github.com/henkelmax/pipez/files/7918027/crash-2022-01-22_17.10.03-server.txt)
[crash-2022-01-22_17.10.57-server.txt](https://github.com/henkelmax/pipez/files/7918028/crash-2022-01-22_17.10.57-server.txt)
[crash-2022-01-22_17.13.24-server.txt](https://github.com/henkelmax/pipez/files/7918029/crash-2022-01-22_17.13.24-server.txt)
[crash-2022-01-22_17.07.37-server.txt](https://github.com/henkelmax/pipez/files/7918030/crash-2022-01-22_17.07.37-server.txt)

**Comment by henkelmax** [comment] 2022-01-22 09:28
Duplicate of #85

**Closed by henkelmax** 2022-01-22 09:28 UTC
Labels: bug

**Comment by D0ucheos** [comment] 2022-01-22 10:37
Cheers.
