### ISSUE TITLE
Pipez Gas Pipes are not compatible with mekanism "infuse types"

### ISSUE THREAD

**Issue by tyler489** [henkelmax/pipez#38] opened 2021-05-18 09:13 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Pipez gas pipes do not connect to mekanism infusers if the side is set to "infuse types"
mekanism gas pipes can extract with this setting but pipes cannot

**Steps to reproduce the issue**
1. Fill a mekanism infuser with redstone, gold, osmium, or diamond
2. set the machine to output in the infuse type tab
3. put a pipes gas pipe next to the machine it doesnt connect
4. put a mekanism gas pipe next to the machine it does connect
**Expected behavior**
The pipes should connect to the machine and extract the infuse types

**Log files**
N/A

**Versions**
- Minecraft version 1.16.
- Forge version 36.1.2
- Mod version 1.2.7

**Other mods**
Stacia Expert pack
**Screenshots (Optional)**
Screenshots of the issue.
![2021-05-18_04 10 49](https://user-images.githubusercontent.com/7015040/118625061-4887d580-b78f-11eb-8e45-ccbab7109d25.png)
![2021-05-18_04 10 57](https://user-images.githubusercontent.com/7015040/118625064-4a519900-b78f-11eb-888e-e50d188f9d83.png)

**Comment by TheNeurotox** [comment] 2021-05-25 06:19
Same issue with slurries type from Mekanism when using gas or universal pipe from Pipez.

**Comment by tyler489** [comment] 2021-05-25 16:44
i though slurries were liquids?

**Comment by TheNeurotox** [comment] 2021-05-26 00:41
For Mekanism, it's "Pressurized tube" the same as for gas. 

For Pipez, Universal, Gas and Fluid are not working.

**Comment by GoldplayEXE** [comment] 2021-07-20 21:38
Has anyone started working on a fix for this?

**Closed** 2022-04-06 11:37 UTC
Labels: wontfix

**Comment by killmetohell** [comment] 2022-04-22 18:51
why won't fix label i don't i should put this up there's an addon for xnet for mek gases and on description it says it uses the slurries api i'm not sure if this the cause but it might be worth looking into it.

**Comment by kiyuzi** [comment] 2022-05-06 16:49
@henkelmax Could you at least state a reason for closing it, or provide a link to a spot where you lay out your reasoning?
